"""initial

Revision ID: 9eed27e1d3de
Revises: 
Create Date: 2026-06-29 11:08:09.780879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9eed27e1d3de'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rut', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('giro', sa.String(length=150), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('logo_filename', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rut')
    )
    op.create_table('valores_uf',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fecha')
    )
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('razon_social', sa.String(length=150), nullable=False),
    sa.Column('rut', sa.String(length=20), nullable=False),
    sa.Column('comentarios', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'rut', name='uq_cliente_empresa_rut')
    )
    op.create_table('cuentas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('moneda', sa.String(length=3), nullable=False),
    sa.Column('saldo_inicial', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'nombre', name='uq_cuenta_empresa_nombre')
    )
    op.create_table('empresa_sii_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('api_key', sa.String(length=255), nullable=True),
    sa.Column('rut_emisor', sa.String(length=20), nullable=True),
    sa.Column('usuario', sa.String(length=20), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('certificado_path', sa.String(length=500), nullable=True),
    sa.Column('certificado_password', sa.String(length=255), nullable=True),
    sa.Column('rut_certificado', sa.String(length=20), nullable=True),
    sa.Column('certificado_b64', sa.Text(), nullable=True),
    sa.Column('ambiente', sa.Integer(), nullable=False),
    sa.Column('rcv_base_url', sa.String(length=255), nullable=True),
    sa.Column('api_base_url', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id')
    )
    op.create_table('empresa_banco_conexiones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('fintoc_api_key', sa.String(length=255), nullable=True),
    sa.Column('fintoc_link_token', sa.String(length=255), nullable=True),
    sa.Column('fintoc_account_id', sa.String(length=100), nullable=True),
    sa.Column('cuenta_contable_id', sa.Integer(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('ultima_sincronizacion', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cuenta_contable_id'], ['cuentas.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('propuestas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('contacto_bgreen', sa.String(length=100), nullable=True),
    sa.Column('cliente_nombre', sa.String(length=150), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('contacto_cliente', sa.String(length=100), nullable=True),
    sa.Column('servicio', sa.String(length=100), nullable=True),
    sa.Column('detalle_servicio', sa.String(length=200), nullable=True),
    sa.Column('superficie_m2', sa.Float(), nullable=True),
    sa.Column('unidades', sa.Float(), nullable=True),
    sa.Column('monto_uf', sa.Float(), nullable=True),
    sa.Column('monto_pesos', sa.Float(), nullable=True),
    sa.Column('fecha_envio', sa.Date(), nullable=True),
    sa.Column('fecha_adjudicacion', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'numero', name='uq_propuesta_empresa_numero')
    )
    op.create_table('proyectos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('superficie', sa.Float(), nullable=False),
    sa.Column('servicio', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('monto_contrato', sa.Float(), nullable=True),
    sa.Column('monto_pagado', sa.Float(), nullable=True),
    sa.Column('monto_facturado', sa.Float(), nullable=True),
    sa.Column('saldo_por_facturar', sa.Float(), nullable=True),
    sa.Column('monto_gastos', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trabajadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('rut', sa.String(length=20), nullable=False),
    sa.Column('apellido_paterno', sa.String(length=100), nullable=False),
    sa.Column('apellido_materno', sa.String(length=100), nullable=True),
    sa.Column('nombres', sa.String(length=100), nullable=False),
    sa.Column('fecha_ingreso', sa.Date(), nullable=False),
    sa.Column('tipo_contrato', sa.String(length=20), nullable=False),
    sa.Column('sueldo_base', sa.Float(), nullable=False),
    sa.Column('sueldo_base_uf', sa.Float(), nullable=True),
    sa.Column('banco', sa.String(length=100), nullable=True),
    sa.Column('cuenta_bancaria', sa.String(length=50), nullable=True),
    sa.Column('nombre_isapre', sa.String(length=100), nullable=True),
    sa.Column('nombre_plan_isapre', sa.String(length=100), nullable=True),
    sa.Column('afp', sa.String(length=50), nullable=False),
    sa.Column('sistema_salud', sa.String(length=20), nullable=False),
    sa.Column('valor_plan_isapre_uf', sa.Float(), nullable=True),
    sa.Column('cuenta_gasto_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['cuenta_gasto_id'], ['cuentas.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('empresa_id', 'rut', name='uq_trabajador_empresa_rut')
    )
    op.create_table('entregas_programadas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('proyecto_id', sa.Integer(), nullable=False),
    sa.Column('fecha_entrega', sa.Date(), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('liquidaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('trabajador_id', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('dias_trabajados', sa.Integer(), nullable=False),
    sa.Column('sueldo_base_proporcional', sa.Float(), nullable=False),
    sa.Column('total_imponible', sa.Float(), nullable=False),
    sa.Column('total_haberes', sa.Float(), nullable=False),
    sa.Column('total_descuentos', sa.Float(), nullable=False),
    sa.Column('alcance_liquido', sa.Float(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('uf_valor', sa.Float(), nullable=True),
    sa.Column('sueldo_base_uf', sa.Float(), nullable=True),
    sa.Column('detalle_calculo', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['trabajador_id'], ['trabajadores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trabajador_id', 'mes', 'anio', name='uq_liquidacion_trabajador_periodo')
    )
    op.create_table('movimientos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('fecha_movimiento', sa.Date(), nullable=False),
    sa.Column('fecha_estado_pago', sa.Date(), nullable=True),
    sa.Column('fecha_facturacion', sa.Date(), nullable=True),
    sa.Column('monto_pesos', sa.Float(), nullable=False),
    sa.Column('centro_costo', sa.String(length=50), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('clase', sa.String(length=20), nullable=False),
    sa.Column('cta_origen_id', sa.Integer(), nullable=False),
    sa.Column('cta_destino_id', sa.Integer(), nullable=False),
    sa.Column('transaccion', sa.String(length=20), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('numero_factura', sa.String(length=50), nullable=True),
    sa.Column('status_pago', sa.String(length=30), nullable=True),
    sa.Column('condicion_pago_dias', sa.Integer(), nullable=True),
    sa.Column('proyecto_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cta_destino_id'], ['cuentas.id'], ),
    sa.ForeignKeyConstraint(['cta_origen_id'], ['cuentas.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tareas_entrega',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('entrega_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('asignado_id', sa.Integer(), nullable=True),
    sa.Column('fecha_limite', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['asignado_id'], ['trabajadores.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['entrega_id'], ['entregas_programadas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tareas_entrega')
    op.drop_table('movimientos')
    op.drop_table('liquidaciones')
    op.drop_table('entregas_programadas')
    op.drop_table('trabajadores')
    op.drop_table('proyectos')
    op.drop_table('propuestas')
    op.drop_table('empresa_banco_conexiones')
    op.drop_table('empresa_sii_config')
    op.drop_table('cuentas')
    op.drop_table('clientes')
    op.drop_table('valores_uf')
    op.drop_table('empresas')
    # ### end Alembic commands ###
